server:
  port: 8083
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
spring.cloud.stream:
  function:
    definition: inventoryProcessor
  bindings:
    inventoryProcessor-in-0:
      destination: order-event
    inventoryProcessor-out-0:
      destination: inventory-event